# Generated by Django 4.1.6 on 2023-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='')),
                ('answer', models.TextField(default='')),
            ],
        ),
    ]
